version: '3.8'

services: 
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file: 
      - ./.env.dev
  
  db:
    image: postgres:14-alpine
    volumne:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: flask_app
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password

volumes: 
  postgres_data