# base image
FROM python:3.10.0-slim-bullseye

# set working directory
WORKDIR /usr/src/app

# set environmental variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# setup python dependencies
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy project files
COPY . /usr/src/app/